apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-spring
  template:
    metadata:
      labels:
        app: hello-spring
    spec:
      containers:
      - name: hello-spring
        image: 383375023402.dkr.ecr.us-east-1.amazonaws.com/ars-marketplace:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
    
---
apiVersion: v1
kind: Service
metadata:
  name: hello-spring-service
spec:
  selector:
    app: hello-spring
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
